export const content = {
  it: {
    nav: {
      about: "Chi sono",
      experience: "Esperienza",
      skills: "Skills e Lingue",
      projects: "Progetti",
      sideprojects: "Progetti Personali",
      education: "Formazione",
      contact: "Contatti",
    },
    hero: {
      label: "Portfolio · CV Interattivo",
      name: "Andrea",
      surname: "Mili",
      role: "ESG & Sustainability Specialist · Monaco di Baviera, Germania",
      cta: "Contattami",
      downloadCv: "Scarica Curriculum Vitae",
      stats: {
        years: { num: "4+", label: "anni di esperienza" },
        projects: { num: "12", label: "progetti completati" },
      },
      tags: ["ESG", "Sostenibilità", "Valuation", "Excel / VBA", "Python", "PowerBI"],
    },
    about: {
      sectionNum: "01",
      sectionTitle: "Chi sono",
      paragraphs: [
        "Sono un <strong>esperto di sostenibilità e ESG</strong> con una forte passione per i dati e per la costruzione di modelli che trasformino numeri complessi in decisioni chiare. Ho maturato esperienza in ambito M&A, valutazione d'azienda e pianificazione strategica.",
        "Nel tempo libero mi interesso di <strong>data analysis</strong> e sviluppo piccoli strumenti per automatizzare attività ripetitive. Mi piace unire rigore analitico e creatività per trovare soluzioni eleganti a problemi concreti.",
        "Sono alla ricerca di nuove sfide in ambienti dinamici dove poter crescere, contribuire e continuare ad imparare ogni giorno.",
        "Aggiungere paragrafo",
      ],
      facts: [],
    },
    experience: {
      sectionNum: "02",
      sectionTitle: "Esperienza",
      items: [
        {
          period: "Gen 2025 — Presente",
          role: "Senior Consultant Sustainable Finance & Public Sector",
          company: "Deloitte · Monaco di Baviera, Germania",
          desc: "Sviluppo di modelli finanziari per la valutazione di potenziali acquisizioni. Supporto al management nella preparazione di presentazioni per il CdA. Analisi di mercato e benchmarking competitivo per 3+ settori industriali.",
        },
        {
          period: "Nov 2022 — Dic 2024",
          role: "Senior Consultant ESG/Sustainability",
          company: "KPMG · Monaco di Baviera, Germania",
          desc: "Partecipazione a progetti di due diligence finanziaria e supporto nella redazione di information memorandum. Gestione database clienti e reportistica periodica.",
        },
        {
          period: "Mar 2021 — Giu 2021",
          role: "Environment, Health and Safety Specialist",
          company: "Tata Consultancy Services · Monaco di Baviera, Germania",
          desc: "Stage curriculare nell'area Corporate Finance. Supporto alla predisposizione di pitch book e analisi di comparabili di mercato.",
        },
      ],
    },
    skills: {
      sectionNum: "03",
      sectionTitle: "Skills e Lingue",
      groups: [
        {
          title: "ESG & Sostenibilità",
          items: [
            { name: "Normative ESG (CSRD, SFDR, Tassonomia UE)", level: "Esperto" },
            { name: "Sustainability Reporting", level: "Esperto" },
            { name: "Double Materiality Assessment", level: "Avanzato" },
            { name: "Financial Modelling & Valuation", level: "Avanzato" },
            { name: "M&A / Due Diligence", level: "Competente" },
          ],
        },
        {
          title: "Strumenti & Software",
          items: [
            { name: "Excel / PowerPoint", level: "Esperto" },
            { name: "Generative AI (Claude, Microsoft Copilot)", level: "Esperto" },
            { name: "PowerBI", level: "Avanzato" },
            { name: "Python (pandas, numpy)", level: "Competente" },
            { name: "SQL", level: "Conoscenza" },
          ],
        },
        {
          title: "Soft Skills",
          items: [
            { name: "Problem Solving", level: "Esperto" },
            { name: "Gestione degli Stakeholder", level: "Esperto" },
            { name: "Storytelling & Presentazioni", level: "Avanzato" },
            { name: "Teamwork", level: "Avanzato" },
          ],
        },
        {
          title: "Lingue",
          items: [
            { name: "Italiano", level: "Madrelingua" },
            { name: "Inglese", level: "Piena padronanza professionale" },
            { name: "Tedesco", level: "Piena padronanza professionale" },
            { name: "Spagnolo", level: "Conoscenza professionale limitata" },
            { name: "Portoghese", level: "Conoscenza elementare" },
            { name: "Gallese", level: "Conoscenza elementare" },
          ],
        },
      ],
    },
    projects: {
      sectionNum: "04",
      sectionTitle: "Progetti",
      cta: "Scopri il progetto",
      items: [
        {
          id: "csrd-reporting",
          symbol: "σ",
          tags: ["Python", "Finance"],
          title: "CSRD Reporting",
          desc: "Tool per l'ottimizzazione di portafogli azionari tramite il modello di Markowitz.",
          fullDesc: "Questo progetto nasce dall'esigenza di applicare la Modern Portfolio Theory in modo pratico e accessibile. Il tool calcola la frontiera efficiente di Markowitz a partire da dati storici scaricati automaticamente via API, e suggerisce l'allocazione ottimale in base al profilo di rischio dell'utente.",
          highlights: ["Calcolo della frontiera efficiente", "Sharpe Ratio ottimizzato", "Importazione dati via Yahoo Finance API", "Visualizzazione interattiva con Plotly"],
          tech: ["Python", "NumPy", "Pandas", "Plotly", "yfinance"],
          link: "https://github.com/mariorossi",
          disclaimer: "Questo progetto è stato sviluppato a scopo personale e non rappresenta in alcun modo il lavoro svolto presso i miei datori di lavoro.",
        },
        {
          id: "lksg-compliance",
          symbol: "Δ",
          tags: ["Excel", "VBA"],
          title: "LkSG Compliance",
          desc: "Template Excel avanzato per la valutazione di società tramite DCF.",
          fullDesc: "Template Excel costruito per semplificare e velocizzare la valutazione di aziende tramite Discounted Cash Flow. Il modello importa automaticamente i dati finanziari storici e proietta i flussi di cassa futuri sulla base di assunzioni personalizzabili.",
          highlights: ["Import automatico bilanci via API", "Scenario analysis (base/bull/bear)", "Report PDF in un click", "Dashboard riassuntiva con grafici"],
          tech: ["Excel", "VBA", "Power Query"],
          link: "https://github.com/mariorossi",
          disclaimer: "Questo progetto è stato sviluppato a scopo personale e non rappresenta in alcun modo il lavoro svolto presso i miei datori di lavoro.",
        },
        {
          id: "ma-monitor",
          symbol: "∑",
          tags: ["PowerBI", "Dashboard"],
          title: "M&A Market Monitor",
          desc: "Dashboard interattiva per il monitoraggio delle operazioni M&A nel mercato italiano.",
          fullDesc: "Dashboard sviluppata in PowerBI per tracciare e analizzare le operazioni M&A sul mercato italiano. I dati vengono aggiornati settimanalmente e permettono di filtrare per settore, deal size, anno e area geografica.",
          highlights: ["Aggiornamento dati settimanale", "Filtri per settore e deal size", "Trend storici 2015–2024", "Export report automatizzato"],
          tech: ["PowerBI", "Power Query", "DAX", "Excel"],
          link: "https://github.com/mariorossi",
          disclaimer: "Questo progetto è stato sviluppato a scopo personale e non rappresenta in alcun modo il lavoro svolto presso i miei datori di lavoro.",
        },
      ],
    },
    sideProjects: {
      sectionNum: "05",
      sectionTitle: "Progetti Personali",
      cta: "Scopri il progetto",
      items: [
        {
          id: "side-project-1",
          symbol: "α",
          tags: ["ESG", "Excel"],
          title: "Progetto 1",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["Excel", "PowerBI"],
          link: "https://github.com/andreamili37",
          disclaimer: "Questo progetto è stato sviluppato a titolo personale.",
        },
        {
          id: "side-project-2",
          symbol: "β",
          tags: ["Python", "Data"],
          title: "Progetto 2",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["Python", "Pandas"],
          link: "https://github.com/andreamili37",
          disclaimer: "Questo progetto è stato sviluppato a titolo personale.",
        },
        {
          id: "side-project-3",
          symbol: "γ",
          tags: ["ESG", "Research"],
          title: "Progetto 3",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["PowerBI", "Excel"],
          link: "https://github.com/andreamili37",
          disclaimer: "Questo progetto è stato sviluppato a titolo personale.",
        },
      ],
    },
    education: {
      sectionNum: "06",
      sectionTitle: "Formazione",
      items: [
        {
          year: "2019 — 2022",
          degree: "MSc Politics and Technology",
          school: "Technical University of Munich · Monaco di Baviera, Germania",
          note: "Tesi su Corporate Valuation in contesti di M&A · Voto finale: 1.8",
        },
        {
          year: "2016 — 2019",
          degree: "BA Political and Administrative Sciences",
          school: "Università degli Studi di Trieste · Trieste, Italia",
          note: "Percorso in Finanza Aziendale · Voto finale: 107/110",
        },
        {
          year: "2023",
          degree: "ESG Expert (EBS)",
          school: "EBS University",
          note: "Certificazione professionale online",
        },
      ],
    },
    contact: {
      sectionNum: "07",
      sectionTitle: "Contatti",
      headline: ["Entriamo in contatto.", "", "", ""],
      links: [
        { type: "email", label: "andreamili@protonmail.com", href: "mailto:andreamili@protonmail.com" },
        { type: "linkedin", label: "linkedin.com/in/andrea-mili/", href: "https://www.linkedin.com/in/andrea-mili/" },
        { type: "phone", label: "+39 333 123 4567", href: "tel:+393331234567" },
      ],
    },
    footer: {
      left: "© 2026 Andrea Mili",
      right: "Costruito con cura · Monaco di Baviera, Germania",
    },
    backToProjects: "← Torna ai progetti",
    siteDisclaimer: "Questo sito costituisce esclusivamente un curriculum vitae interattivo a scopo di presentazione professionale. Non rappresenta né implica l'offerta di servizi di consulenza o di qualsiasi altra prestazione professionale, a titolo oneroso o gratuito. Nessuna informazione contenuta in questo sito è riconducibile a dati riservati, metodologie proprietarie o informazioni confidenziali relative ad aziende o clienti con cui ho collaborato.",
  },

  en: {
    nav: {
      about: "About",
      experience: "Experience",
      skills: "Skills and Languages",
      projects: "Projects",
      sideprojects: "Side Projects",
      education: "Education",
      contact: "Contact",
    },
    hero: {
      label: "Portfolio · Interactive CV",
      name: "Andrea",
      surname: "Mili",
      role: "ESG & Sustainability Specialist · Munich, Germany",
      cta: "Get in touch",
      downloadCv: "Download CV",
      stats: {
        years: { num: "4+", label: "years of experience" },
        projects: { num: "12", label: "completed projects" },
      },
      tags: ["ESG", "Corporate Sustainability", "Compliance", "Strategy", "Python", "PowerBI"],
    },
    about: {
      sectionNum: "01",
      sectionTitle: "About me",
      paragraphs: [
        "I am an <strong>ESG and Sustainability Specialist</strong> with extensive experience in the corporate sustainability space.",
        "Originally from Italy, my background is in political science, a discipline that provides me with the skills to think in an interconnected way and to develop strategies . After gaining my Bachelor's Degree at the University of Trieste in Italy, I pursued a Master's Degree at the Technical University of Munich, one of the world's leading universities, where I specialised in environmental policy and sustainable transitions. That multidisciplinary foundation I developed throughout my academic experience is what sets my approach apart. Having been trained to think across boundaries allows me to bring solutions that a more narrowly focused background might not. My professional career started in 2021 and ever since then I work daily with commitment on the sustainability topic, delivering high quality products which are the results of my passion for the topic. However, my high capacity for adaptability, shaped by my experience of never living inside my comfort zone, allows me to undertake projects whose topic sits outside my area of expertise.",
        "Outside of work, I dedicate most of my free time to my passion for <strong>literature</strong>. From Russian novels, to Italian classics and non-fiction books about politics and economics: reading is for me a way to reconnect with my inner nature of <strong>storyteller</strong>, which is something I used to explore by auto-producing podcasts and that I am currently fostering through <strong>creative writing</strong>. While I recently started exploring blogging on Substack, I am also currently writing a novel set in Wales, a land I visit every summer and to which I feel an innate connection, that led me to study the Welsh language.",
        "Aggiungere paragrafo",
      ],
      facts: [],
    },
    experience: {
      sectionNum: "02",
      sectionTitle: "Professional Experience",
      items: [
        {
          period: "Jan 2025 — Present",
          role: "Senior Consultant Sustainable Finance & Public Sector",
          company: "Deloitte · Munich, Germany",
          desc: "Audit of ESRS reports developed by prominent actors in the German financial landscape. Data-driven analyses on the status of ESRS implementation across financial sector companies in Europe. Collaboration in projects contributing to the digitalisation of German public institutions.",
        },
        {
          period: "Nov 2022 — Dec 2024",
          role: "Senior Associate ESG/Sustainability",
          company: "KPMG · Munich, Germany",
          desc: "Focus on major European ESG regulations, especially on CSRD and EU Taxonomy. Implementation of ESG aspects into clients' Internal Control Systems. Development of interactive data-based tools on ESRS preparation to be used as selling point. ",
        },
        {
          period: "May 2021 — Jun 2022",
          role: "Environment, Health and Safety Officer",
          company: "Tata Consultancy Services · Munich, Germany",
          desc: "ESG data collection for all the German offices of the company. Conduction of audits to ensure of the ISO 14001 and ISO 45001 compliance of the offices. Implementation and monitoring of German occupational health and safety laws (especially during the Covid pandemic).",
        },
      ],
    },
    skills: {
      sectionNum: "03",
      sectionTitle: "Skills and Languages",
      groups: [
        {
          title: "ESG & Sustainability",
          items: [
            { name: "EU ESG Regulations (CSRD, SFDR, EU Taxonomy)", level: "Expert" },
            { name: "Sustainability Reporting", level: "Expert" },
            { name: "Global ESG Regulations (ISSB, GRI, TCFD)", level: "Advanced" },
            { name: "Financial Modelling & Valuation", level: "Advanced" },
            { name: "M&A / Due Diligence", level: "Proficient" },
          ],
        },
        {
          title: "Tools & Software",
          items: [
            { name: "MS Office Suite (Excel, PowerPoint, Word)", level: "Expert" },
            { name: "Generative AI (Claude, Microsoft Copilot)", level: "Expert" },
            { name: "PowerBI", level: "Proficient" },
            { name: "Python (pandas, numpy)", level: "Proficient" },
            { name: "SQL", level: "Familiar" },
          ],
        },
        {
          title: "Soft Skills",
          items: [
            { name: "Problem Solving", level: "Expert" },
            { name: "Stakeholder Management", level: "Expert" },
            { name: "Storytelling & Presentations", level: "Advanced" },
            { name: "Teamwork", level: "Advanced" },
          ],
        },
        {
          title: "Languages",
          items: [
            { name: "Italian", level: "Native" },
            { name: "English", level: "Full professional proficiency" },
            { name: "German", level: "Full professional proficiency" },
            { name: "Spanish", level: "Limited professional proficiency" },
            { name: "Portuguese", level: "Elementary proficiency" },
            { name: "Welsh", level: "Elementary proficiency" },
          ],
        },
      ],
    },
    projects: {
      sectionNum: "04",
      sectionTitle: "Projects",
      cta: "Explore project",
      items: [
        {
          id: "csrd-reporting",
          symbol: "σ",
          tags: ["CSRD", "Compliance"],
          title: "CSRD Reporting",
          desc: "Supporting a large German company with all the necessary steps to produce a fully fledged CSRD report.",
          fullDesc: "Due to the Corporate Sustainability Directive (CSRD), ",
          highlights: ["Analysis of the company's structure", "Development of a concept for the production of a comprehensive Double Materiality Analysis", "Data import via Yahoo Finance API", "Interactive visualisation with Plotly"],
          tech: ["CSRD", "ESG", "Sustainability Reporting", "Sustainability Strategy", "Data Analysis"],
          link: "https://github.com/mariorossi",
          disclaimer: "The information in this section merely depicts my role within the project to showcase how I contributed to its successful realisation. It does not, in any way or form, indicate any client-sensitive information, nor any specific methodology developed within the company where I worked on this project.",
        },
        {
          id: "lksg-compliance",
          symbol: "Δ",
          tags: ["Excel", "VBA"],
          title: "Automated DCF Model",
          desc: "Advanced Excel template for company valuation via DCF.",
          fullDesc: "An Excel template built to simplify and speed up company valuation via Discounted Cash Flow. The model automatically imports historical financial data and projects future cash flows based on customisable assumptions.",
          highlights: ["Automatic financial statement import via API", "Scenario analysis (base/bull/bear)", "One-click PDF report", "Summary dashboard with charts"],
          tech: ["Excel", "VBA", "Power Query"],
          link: "https://github.com/mariorossi",
          disclaimer: "The information in this section merely depicts my role within the project to showcase how I contributed to its successful realisation. It does not, in any way or form, indicate any client-sensitive information, nor any specific methodology developed within the company where I worked on this project.",
        },
        {
          id: "ma-monitor",
          symbol: "∑",
          tags: ["PowerBI", "Dashboard"],
          title: "Non-financial reports audit",
          desc: "Interactive dashboard for monitoring M&A activity in the Italian market.",
          fullDesc: "A PowerBI dashboard developed to track and analyse M&A transactions in the Italian market. Data is updated weekly and can be filtered by sector, deal size, year and geography.",
          highlights: ["Weekly data updates", "Filters by sector and deal size", "Historical trends 2015–2024", "Automated report export"],
          tech: ["PowerBI", "Power Query", "DAX", "Excel"],
          link: "https://github.com/mariorossi",
          disclaimer: "The information in this section merely depicts my role within the project to showcase how I contributed to its successful realisation. It does not, in any way or form, indicate any client-sensitive information, nor any specific methodology developed within the company where I worked on this project.",
        },
      ],
    },
    sideProjects: {
      sectionNum: "05",
      sectionTitle: "Side Projects",
      cta: "Explore the project",
      items: [
        {
          id: "side-project-1",
          symbol: "α",
          tags: ["ESG", "Excel"],
          title: "Progetto 1",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["Excel", "PowerBI"],
          link: "https://github.com/andreamili37",
          disclaimer: "This project has been produced in my free time, using exclusively publicly available information (which are referenced), with my personal devices and intellectual knowledge. It does not, in any way or form, utilize client-specific information nor methodologies, knowledge or material produced by the companies I have been employed at. Moreover, this project does not represent any consultancy service I performed as freelancer: it is merely a way to showcase my skills and my interests.",
        },
        {
          id: "side-project-2",
          symbol: "β",
          tags: ["Python", "Data"],
          title: "Progetto 2",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["Python", "Pandas"],
          link: "https://github.com/andreamili37",
          disclaimer: "This project has been produced in my free time, using exclusively publicly available information (which are referenced), with my personal devices and intellectual knowledge. It does not, in any way or form, utilize client-specific information nor methodologies, knowledge or material produced by the companies I have been employed at. Moreover, this project does not represent any consultancy service I performed as freelancer: it is merely a way to showcase my skills and my interests.",
        },
        {
          id: "side-project-3",
          symbol: "γ",
          tags: ["ESG", "Research"],
          title: "Progetto 3",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["PowerBI", "Excel"],
          link: "https://github.com/andreamili37",
          disclaimer: "This project has been produced in my free time, using exclusively publicly available information (which are referenced), with my personal devices and intellectual knowledge. It does not, in any way or form, utilize client-specific information nor methodologies, knowledge or material produced by the companies I have been employed at. Moreover, this project does not represent any consultancy service I performed as freelancer: it is merely a way to showcase my skills and my interests.",
        },
      ],
    },
    education: {
      sectionNum: "06",
      sectionTitle: "Education",
      items: [
        {
          year: "2019 — 2022",
          degree: "MSc Politics and Technology",
          school: "Technical University of Munich · Germany",
          note: "Focus on Sustainability Transition and Corporate Sustainability · Final Grade: 1.8",
        },
        {
          year: "2015 — 2019",
          degree: "BA Political and Administrative Sciences",
          school: "Università degli Studi di Trieste",
          note: "Focus on EU Institutions and Policy Analysis · Final Grade: 107/110",
        },
        {
          year: "2023",
          degree: "ESG Expert (EBS)",
          school: "EBS University",
          note: "Professional ESG certification",
        },
      ],
    },
    contact: {
      sectionNum: "07",
      sectionTitle: "Contact",
      headline: ["Let's connect.", "", "", ""],
      links: [
        { type: "email", label: "andreamili@protonmail.com", href: "mailto:andreamili@protonmail.com" },
        { type: "linkedin", label: "linkedin.com/in/andrea-mili/", href: "https://www.linkedin.com/in/andrea-mili/" },
        { type: "phone", label: "+49 15141219336", href: "tel:+4915141219336" },
      ],
    },
    footer: {
      left: "© 2026 Andrea Mili",
      right: "Buten un Binnen, Wagen un Winnen · Munich, Germany",
    },
    backToProjects: "← Back to projects",
    siteDisclaimer: "This website constitutes solely an interactive curriculum vitae for professional presentation purposes. It does not represent or imply the offer of any consulting or professional services, whether paid or unpaid. No information contained in this website is traceable to confidential data, proprietary methodologies, or sensitive information relating to companies or clients I have worked with.",
  },

  de: {
    nav: {
      about: "Über mich",
      experience: "Erfahrung",
      skills: "Skills und Sprachen",
      projects: "Projekte",
      sideprojects: "Eigenprojekte",
      education: "Ausbildung",
      contact: "Kontakt",
    },
    hero: {
      label: "Portfolio · Interaktiver Lebenslauf",
      name: "Andrea",
      surname: "Mili",
      role: "ESG- und Nachhaltigkeitsexperte · München, Deutschland",
      cta: "Kontakt aufnehmen",
      downloadCv: "Lebenslauf herunterladen",
      stats: {
        years: { num: "4+", label: "Jahre Erfahrung" },
        projects: { num: "20", label: "abgeschlossene Projekte" },
      },
      tags: ["ESG", "Nachhaltigkeit", "Compliance", "Excel / VBA", "Python", "PowerBI"],
    },
    about: {
      sectionNum: "01",
      sectionTitle: "Über mich",
      paragraphs: [
        "Ich bin ein <strong>Finanzanalyst</strong> mit einer starken Leidenschaft für Daten und die Erstellung von Modellen, die komplexe Zahlen in klare Entscheidungen umwandeln. Ich habe Erfahrung in den Bereichen M&A, Unternehmensbewertung und strategische Planung gesammelt.",
        "In meiner Freizeit interessiere ich mich für <strong>Datenanalyse</strong> und entwickle kleine Tools zur Automatisierung repetitiver Aufgaben. Ich verbinde analytische Strenge mit Kreativität, um elegante Lösungen für konkrete Probleme zu finden.",
        "Ich suche nach neuen Herausforderungen in dynamischen Umfeldern, in denen ich wachsen, beitragen und jeden Tag dazulernen kann.",
        "Aggiungere paragrafo",
      ],
      facts: [],
    },
    experience: {
      sectionNum: "02",
      sectionTitle: "Erfahrung",
      items: [
        {
          period: "Jan 2025 — Heute",
          role: "Senior Consultant Sustainable Finance & Public Sector",
          company: "Deloitte · München, Deutschland",
          desc: "Entwicklung von Finanzmodellen zur Bewertung potenzieller Akquisitionen. Unterstützung des Managements bei der Vorbereitung von Vorstandspräsentationen. Marktanalyse und Wettbewerbsvergleiche in 3+ Industriesektoren.",
        },
        {
          period: "Nov 2022 — Dez 2024",
          role: "Senior Associate ESG/Sustainability",
          company: "KPMG · München, Deutschland",
          desc: "Mitarbeit an Financial Due Diligence Projekten und Unterstützung bei der Erstellung von Information Memoranda. Kundendatenbankpflege und periodisches Reporting.",
        },
        {
          period: "Mai 2021 — Jun 2022",
          role: "Praktikum — Finance Department",
          company: "Tata Consultancy Services · München, Deutschland",
          desc: "Curriculares Praktikum im Bereich Corporate Finance. Unterstützung bei der Erstellung von Pitch Books und Marktvergleichsanalysen.",
        },
      ],
    },
    skills: {
      sectionNum: "03",
      sectionTitle: "Skills und Sprachen",
      groups: [
        {
          title: "ESG & Nachhaltigkeit",
          items: [
            { name: "ESG-Regularien (CSRD, SFDR, EU-Taxonomie)", level: "Experte" },
            { name: "Nachhaltigkeitsberichterstattung", level: "Experte" },
            { name: "Doppelte Wesentlichkeitsanalyse", level: "Fortgeschritten" },
            { name: "Financial Modelling & Bewertung", level: "Fortgeschritten" },
            { name: "M&A / Due Diligence", level: "Kompetent" },
          ],
        },
        {
          title: "Tools & Software",
          items: [
            { name: "Excel / PowerPoint", level: "Experte" },
            { name: "Generative KI (Claude, Microsoft Copilot)", level: "Experte" },
            { name: "PowerBI", level: "Fortgeschritten" },
            { name: "Python (pandas, numpy)", level: "Kompetent" },
            { name: "SQL", level: "Vertraut" },
          ],
        },
        {
          title: "Soft Skills",
          items: [
            { name: "Problemlösung", level: "Experte" },
            { name: "Stakeholder-Management", level: "Experte" },
            { name: "Storytelling & Präsentationen", level: "Fortgeschritten" },
            { name: "Teamarbeit", level: "Fortgeschritten" },
          ],
        },
        {
          title: "Sprachen",
          items: [
            { name: "Italienisch", level: "Muttersprache" },
            { name: "Englisch", level: "Verhandlungssicher" },
            { name: "Deutsch", level: "Verhandlungssicher" },
            { name: "Spanisch", level: "Gute Kenntnisse" },
            { name: "Portugiesisch", level: "Grundkenntnisse" },
            { name: "Walisisch", level: "Grundkenntnisse" },
          ],
        },
      ],
    },
    projects: {
      sectionNum: "04",
      sectionTitle: "Projekte",
      cta: "Projekt erkunden",
      items: [
        {
          id: "csrd-reporting",
          symbol: "σ",
          tags: ["Python", "Finance"],
          title: "ESG-Ratings Vergleich",
          desc: "Tool zur Optimierung von Aktienportfolios mit dem Markowitz-Modell.",
          fullDesc: "Dieses Projekt entstand aus dem Bedarf, die Modern Portfolio Theory praktisch und zugänglich anzuwenden. Das Tool berechnet die Markowitz-Effizienzgrenze aus historischen Daten, die automatisch über eine API heruntergeladen werden, und empfiehlt die optimale Allokation basierend auf dem Risikoprofil des Nutzers.",
          highlights: ["Berechnung der Effizienzgrenze", "Optimierte Sharpe Ratio", "Datenimport über Yahoo Finance API", "Interaktive Visualisierung mit Plotly"],
          tech: ["Python", "NumPy", "Pandas", "Plotly", "yfinance"],
          link: "https://github.com/mariorossi",
          disclaimer: "Questo progetto è stato sviluppato a scopo personale e non rappresenta in alcun modo il lavoro svolto presso i miei datori di lavoro.",
        },
        {
          id: "lksg-compliance",
          symbol: "Δ",
          tags: ["Excel", "VBA"],
          title: "Automatisiertes DCF-Modell",
          desc: "Erweitertes Excel-Template zur Unternehmensbewertung per DCF.",
          fullDesc: "Ein Excel-Template zur Vereinfachung und Beschleunigung der Unternehmensbewertung per Discounted Cash Flow. Das Modell importiert automatisch historische Finanzdaten und projiziert zukünftige Cashflows auf Basis anpassbarer Annahmen.",
          highlights: ["Automatischer Bilanzimport via API", "Szenarioanalyse (base/bull/bear)", "PDF-Bericht per Knopfdruck", "Übersichts-Dashboard mit Diagrammen"],
          tech: ["Excel", "VBA", "Power Query"],
          link: "https://github.com/mariorossi",
          disclaimer: "Questo progetto è stato sviluppato a scopo personale e non rappresenta in alcun modo il lavoro svolto presso i miei datori di lavoro.",
        },
        {
          id: "ma-monitor",
          symbol: "∑",
          tags: ["PowerBI", "Dashboard"],
          title: "M&A Market Monitor",
          desc: "Interaktives Dashboard zur Überwachung von M&A-Aktivitäten im italienischen Markt.",
          fullDesc: "Ein in PowerBI entwickeltes Dashboard zur Verfolgung und Analyse von M&A-Transaktionen auf dem italienischen Markt. Die Daten werden wöchentlich aktualisiert und können nach Sektor, Deal-Größe, Jahr und Region gefiltert werden.",
          highlights: ["Wöchentliche Datenaktualisierung", "Filter nach Sektor und Deal-Größe", "Historische Trends 2015–2024", "Automatisierter Berichtsexport"],
          tech: ["PowerBI", "Power Query", "DAX", "Excel"],
          link: "https://github.com/mariorossi",
          disclaimer: "Questo progetto è stato sviluppato a scopo personale e non rappresenta in alcun modo il lavoro svolto presso i miei datori di lavoro.",
        },
      ],
    },
    sideProjects: {
      sectionNum: "05",
      sectionTitle: "Eigenprojekte",
      cta: "Projekt erkunden",
      items: [
        {
          id: "side-project-1",
          symbol: "α",
          tags: ["ESG", "Excel"],
          title: "Progetto 1",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["Excel", "PowerBI"],
          link: "https://github.com/andreamili37",
          disclaimer: "Questo progetto è stato sviluppato a titolo personale.",
        },
        {
          id: "side-project-2",
          symbol: "β",
          tags: ["Python", "Data"],
          title: "Progetto 2",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["Python", "Pandas"],
          link: "https://github.com/andreamili37",
          disclaimer: "Questo progetto è stato sviluppato a titolo personale.",
        },
        {
          id: "side-project-3",
          symbol: "γ",
          tags: ["ESG", "Research"],
          title: "Progetto 3",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["PowerBI", "Excel"],
          link: "https://github.com/andreamili37",
          disclaimer: "Questo progetto è stato sviluppato a titolo personale.",
        },
      ],
    },
    education: {
      sectionNum: "06",
      sectionTitle: "Ausbildung",
      items: [
        {
          year: "2019 — 2022",
          degree: "MSc Politics and Technology",
          school: "Technische Universität München · München, Deutschland",
          note: "Schwerpunkt Nachhaltigkeitstransition · Abschlussnote: 1.8",
        },
        {
          year: "2016 — 2019",
          degree: "BA Politikwissenschaft",
          school: "Universität Triest · Triest, Italien",
          note: "Schwerpunkt EU-Institutionen und Politikanalyse · Abschlussnote: 107/110",
        },
        {
          year: "2023",
          degree: "ESG Expert (EBS)",
          school: "EBS University",
          note: "Professionelle ESG-Zertifizierung",
        },
      ],
    },
    contact: {
      sectionNum: "07",
      sectionTitle: "Kontakt",
      headline: ["Lassen Sie uns etwas", "", "Bedeutendes", "gemeinsam aufbauen."],
      links: [
        { type: "email", label: "andreamili@protonmail.com", href: "mailto:andreamili@protonmail.com" },
        { type: "linkedin", label: "linkedin.com/in/andrea-mili/", href: "https://www.linkedin.com/in/andrea-mili/" },
        { type: "phone", label: "+39 333 123 4567", href: "tel:+393331234567" },
      ],
    },
    footer: {
      left: "© 2026 Andrea Mili",
      right: "Mit Sorgfalt gebaut · München, Deutschland",
    },
    backToProjects: "← Zurück zu den Projekten",
    siteDisclaimer: "Diese Website dient ausschließlich als interaktiver Lebenslauf zu professionellen Präsentationszwecken. Sie stellt weder ein Angebot von Beratungs- oder sonstigen professionellen Dienstleistungen dar, noch impliziert sie ein solches, weder entgeltlich noch unentgeltlich. Keine der auf dieser Website enthaltenen Informationen ist auf vertrauliche Daten, proprietäre Methoden oder sensible Informationen zurückzuführen, die Unternehmen oder Kunden betreffen, mit denen ich zusammengearbeitet habe.",
  },
};