export const content = {
  it: {
    nav: {
      about: "Chi sono",
      experience: "Esperienza",
      skills: "Skills",
      projects: "Progetti",
      education: "Formazione",
      contact: "Contatti",
    },
    hero: {
      label: "Portfolio · CV Interattivo",
      name: "Mario",
      surname: "Rossi",
      role: "Finance & Strategy Analyst · Milano",
      cta: "Contattami",
      stats: {
        years: { num: "4+", label: "anni di esperienza" },
        projects: { num: "12", label: "progetti completati" },
      },
      tags: ["Financial Modelling", "M&A", "Valuation", "Excel / VBA", "Python", "PowerBI"],
    },
    about: {
      sectionNum: "01",
      sectionTitle: "Chi sono",
      paragraphs: [
        "Sono un <strong>analista finanziario</strong> con una forte passione per i dati e per la costruzione di modelli che trasformino numeri complessi in decisioni chiare. Ho maturato esperienza in ambito M&A, valutazione d'azienda e pianificazione strategica.",
        "Nel tempo libero mi interesso di <strong>data analysis</strong> e sviluppo piccoli strumenti per automatizzare attività ripetitive. Mi piace unire rigore analitico e creatività per trovare soluzioni eleganti a problemi concreti.",
        "Sono alla ricerca di nuove sfide in ambienti dinamici dove poter crescere, contribuire e continuare ad imparare ogni giorno.",
      ],
      facts: [
        { label: "Disponibilità", value: "Immediata · Full-time" },
        { label: "Sede", value: "Milano · Disponibile a trasferte" },
        { label: "Lingue", value: "Italiano · Inglese (C1) · Francese (B1)" },
        { label: "Interessi", value: "Mercati finanziari · Data science · Running" },
      ],
    },
    experience: {
      sectionNum: "02",
      sectionTitle: "Esperienza",
      items: [
        {
          period: "Gen 2023 — Presente",
          role: "Finance Analyst",
          company: "Società SpA · Milano",
          desc: "Sviluppo di modelli finanziari per la valutazione di potenziali acquisizioni. Supporto al management nella preparazione di presentazioni per il CdA. Analisi di mercato e benchmarking competitivo per 3+ settori industriali.",
        },
        {
          period: "Lug 2021 — Dic 2022",
          role: "Junior Analyst",
          company: "Consulting Firm Srl · Milano",
          desc: "Partecipazione a progetti di due diligence finanziaria e supporto nella redazione di information memorandum. Gestione database clienti e reportistica periodica.",
        },
        {
          period: "Mar 2021 — Giu 2021",
          role: "Stage — Finance Department",
          company: "Banca XYZ · Milano",
          desc: "Stage curriculare nell'area Corporate Finance. Supporto alla predisposizione di pitch book e analisi di comparabili di mercato.",
        },
      ],
    },
    skills: {
      sectionNum: "03",
      sectionTitle: "Skills",
      groups: [
        {
          title: "Finance & Analisi",
          items: [
            { name: "Financial Modelling", pct: 95 },
            { name: "Valuation (DCF, Comps)", pct: 90 },
            { name: "M&A / Due Diligence", pct: 80 },
            { name: "Corporate Finance", pct: 85 },
          ],
        },
        {
          title: "Tool & Software",
          items: [
            { name: "Excel / VBA", pct: 95 },
            { name: "PowerBI / Tableau", pct: 80 },
            { name: "Python (pandas, numpy)", pct: 70 },
            { name: "Bloomberg / Refinitiv", pct: 75 },
          ],
        },
        {
          title: "Soft Skills",
          items: [
            { name: "Problem Solving", pct: 95 },
            { name: "Comunicazione", pct: 85 },
            { name: "Teamwork", pct: 90 },
            { name: "Presentazioni", pct: 88 },
          ],
        },
      ],
    },
    projects: {
      sectionNum: "04",
      sectionTitle: "Progetti",
      cta: "Scopri il progetto",
      items: [
        {
          id: "portfolio-optimizer",
          symbol: "σ",
          tags: ["Python", "Finance"],
          title: "Portfolio Optimizer",
          desc: "Tool per l'ottimizzazione di portafogli azionari tramite il modello di Markowitz.",
          fullDesc: "Questo progetto nasce dall'esigenza di applicare la Modern Portfolio Theory in modo pratico e accessibile. Il tool calcola la frontiera efficiente di Markowitz a partire da dati storici scaricati automaticamente via API, e suggerisce l'allocazione ottimale in base al profilo di rischio dell'utente.",
          highlights: ["Calcolo della frontiera efficiente", "Sharpe Ratio ottimizzato", "Importazione dati via Yahoo Finance API", "Visualizzazione interattiva con Plotly"],
          tech: ["Python", "NumPy", "Pandas", "Plotly", "yfinance"],
          link: "https://github.com/mariorossi",
        },
        {
          id: "dcf-model",
          symbol: "Δ",
          tags: ["Excel", "VBA"],
          title: "DCF Model Automatizzato",
          desc: "Template Excel avanzato per la valutazione di società tramite DCF.",
          fullDesc: "Template Excel costruito per semplificare e velocizzare la valutazione di aziende tramite Discounted Cash Flow. Il modello importa automaticamente i dati finanziari storici e proietta i flussi di cassa futuri sulla base di assunzioni personalizzabili.",
          highlights: ["Import automatico bilanci via API", "Scenario analysis (base/bull/bear)", "Report PDF in un click", "Dashboard riassuntiva con grafici"],
          tech: ["Excel", "VBA", "Power Query"],
          link: "https://github.com/mariorossi",
        },
        {
          id: "ma-monitor",
          symbol: "∑",
          tags: ["PowerBI", "Dashboard"],
          title: "M&A Market Monitor",
          desc: "Dashboard interattiva per il monitoraggio delle operazioni M&A nel mercato italiano.",
          fullDesc: "Dashboard sviluppata in PowerBI per tracciare e analizzare le operazioni M&A sul mercato italiano. I dati vengono aggiornati settimanalmente e permettono di filtrare per settore, deal size, anno e area geografica.",
          highlights: ["Aggiornamento dati settimanale", "Filtri per settore e deal size", "Trend storici 2015–2024", "Export report automatizzato"],
          tech: ["PowerBI", "Power Query", "DAX", "Excel"],
          link: "https://github.com/mariorossi",
        },
      ],
    },
    education: {
      sectionNum: "05",
      sectionTitle: "Formazione",
      items: [
        {
          year: "2019 — 2021",
          degree: "MSc Finance",
          school: "Università Bocconi · Milano",
          note: "Tesi su Corporate Valuation in contesti di M&A · 110/110",
        },
        {
          year: "2016 — 2019",
          degree: "BSc Economia e Management",
          school: "Università degli Studi di Milano",
          note: "Percorso in Finanza Aziendale · 108/110",
        },
        {
          year: "2022",
          degree: "CFA Level I",
          school: "CFA Institute",
          note: "Superato con percentile 90+ · Level II in corso",
        },
        {
          year: "2020",
          degree: "Financial Modelling & Valuation",
          school: "FMVA® — Corporate Finance Institute",
          note: "Certificazione professionale online",
        },
      ],
    },
    contact: {
      sectionNum: "06",
      sectionTitle: "Contatti",
      headline: ["Costruiamo qualcosa", "di", "importante", "insieme."],
      links: [
        { type: "email", label: "mario.rossi@email.com", href: "mailto:mario.rossi@email.com" },
        { type: "linkedin", label: "linkedin.com/in/mario-rossi", href: "https://linkedin.com/in/mario-rossi" },
        { type: "phone", label: "+39 333 123 4567", href: "tel:+393331234567" },
      ],
    },
    footer: {
      left: "© 2026 Mario Rossi",
      right: "Costruito con cura · Milano, Italia",
    },
    backToProjects: "← Torna ai progetti",
  },

  en: {
    nav: {
      about: "About",
      experience: "Experience",
      skills: "Skills",
      projects: "Projects",
      education: "Education",
      contact: "Contact",
    },
    hero: {
      label: "Portfolio · Interactive CV",
      name: "Mario",
      surname: "Rossi",
      role: "Finance & Strategy Analyst · Milan",
      cta: "Get in touch",
      stats: {
        years: { num: "4+", label: "years of experience" },
        projects: { num: "12", label: "completed projects" },
      },
      tags: ["Financial Modelling", "M&A", "Valuation", "Excel / VBA", "Python", "PowerBI"],
    },
    about: {
      sectionNum: "01",
      sectionTitle: "About me",
      paragraphs: [
        "I am a <strong>financial analyst</strong> with a strong passion for data and building models that turn complex numbers into clear decisions. I have gained experience in M&A, company valuation and strategic planning.",
        "In my free time I am interested in <strong>data analysis</strong> and develop small tools to automate repetitive tasks. I enjoy combining analytical rigour and creativity to find elegant solutions to concrete problems.",
        "I am looking for new challenges in dynamic environments where I can grow, contribute and keep learning every day.",
      ],
      facts: [
        { label: "Availability", value: "Immediate · Full-time" },
        { label: "Location", value: "Milan · Open to relocation" },
        { label: "Languages", value: "Italian · English (C1) · French (B1)" },
        { label: "Interests", value: "Financial markets · Data science · Running" },
      ],
    },
    experience: {
      sectionNum: "02",
      sectionTitle: "Experience",
      items: [
        {
          period: "Jan 2023 — Present",
          role: "Finance Analyst",
          company: "Società SpA · Milan",
          desc: "Development of financial models for the evaluation of potential acquisitions. Support to management in preparing board presentations. Market analysis and competitive benchmarking across 3+ industrial sectors.",
        },
        {
          period: "Jul 2021 — Dec 2022",
          role: "Junior Analyst",
          company: "Consulting Firm Srl · Milan",
          desc: "Participation in financial due diligence projects and support in drafting information memoranda. Client database management and periodic reporting.",
        },
        {
          period: "Mar 2021 — Jun 2021",
          role: "Intern — Finance Department",
          company: "Banca XYZ · Milan",
          desc: "Curricular internship in the Corporate Finance division. Support in preparing pitch books and market comparables analysis.",
        },
      ],
    },
    skills: {
      sectionNum: "03",
      sectionTitle: "Skills",
      groups: [
        {
          title: "Finance & Analysis",
          items: [
            { name: "Financial Modelling", pct: 95 },
            { name: "Valuation (DCF, Comps)", pct: 90 },
            { name: "M&A / Due Diligence", pct: 80 },
            { name: "Corporate Finance", pct: 85 },
          ],
        },
        {
          title: "Tools & Software",
          items: [
            { name: "Excel / VBA", pct: 95 },
            { name: "PowerBI / Tableau", pct: 80 },
            { name: "Python (pandas, numpy)", pct: 70 },
            { name: "Bloomberg / Refinitiv", pct: 75 },
          ],
        },
        {
          title: "Soft Skills",
          items: [
            { name: "Problem Solving", pct: 95 },
            { name: "Communication", pct: 85 },
            { name: "Teamwork", pct: 90 },
            { name: "Presentations", pct: 88 },
          ],
        },
      ],
    },
    projects: {
      sectionNum: "04",
      sectionTitle: "Projects",
      cta: "Explore project",
      items: [
        {
          id: "portfolio-optimizer",
          symbol: "σ",
          tags: ["Python", "Finance"],
          title: "Portfolio Optimizer",
          desc: "A tool for optimising equity portfolios using the Markowitz model.",
          fullDesc: "This project was born from the need to apply Modern Portfolio Theory in a practical and accessible way. The tool calculates the Markowitz efficient frontier from historical data downloaded automatically via API, and suggests the optimal allocation based on the user's risk profile.",
          highlights: ["Efficient frontier calculation", "Optimised Sharpe Ratio", "Data import via Yahoo Finance API", "Interactive visualisation with Plotly"],
          tech: ["Python", "NumPy", "Pandas", "Plotly", "yfinance"],
          link: "https://github.com/mariorossi",
        },
        {
          id: "dcf-model",
          symbol: "Δ",
          tags: ["Excel", "VBA"],
          title: "Automated DCF Model",
          desc: "Advanced Excel template for company valuation via DCF.",
          fullDesc: "An Excel template built to simplify and speed up company valuation via Discounted Cash Flow. The model automatically imports historical financial data and projects future cash flows based on customisable assumptions.",
          highlights: ["Automatic financial statement import via API", "Scenario analysis (base/bull/bear)", "One-click PDF report", "Summary dashboard with charts"],
          tech: ["Excel", "VBA", "Power Query"],
          link: "https://github.com/mariorossi",
        },
        {
          id: "ma-monitor",
          symbol: "∑",
          tags: ["PowerBI", "Dashboard"],
          title: "M&A Market Monitor",
          desc: "Interactive dashboard for monitoring M&A activity in the Italian market.",
          fullDesc: "A PowerBI dashboard developed to track and analyse M&A transactions in the Italian market. Data is updated weekly and can be filtered by sector, deal size, year and geography.",
          highlights: ["Weekly data updates", "Filters by sector and deal size", "Historical trends 2015–2024", "Automated report export"],
          tech: ["PowerBI", "Power Query", "DAX", "Excel"],
          link: "https://github.com/mariorossi",
        },
      ],
    },
    education: {
      sectionNum: "05",
      sectionTitle: "Education",
      items: [
        {
          year: "2019 — 2021",
          degree: "MSc Finance",
          school: "Università Bocconi · Milan",
          note: "Thesis on Corporate Valuation in M&A contexts · 110/110",
        },
        {
          year: "2016 — 2019",
          degree: "BSc Economics & Management",
          school: "Università degli Studi di Milano",
          note: "Corporate Finance track · 108/110",
        },
        {
          year: "2022",
          degree: "CFA Level I",
          school: "CFA Institute",
          note: "Passed at 90th+ percentile · Level II in progress",
        },
        {
          year: "2020",
          degree: "Financial Modelling & Valuation",
          school: "FMVA® — Corporate Finance Institute",
          note: "Professional online certification",
        },
      ],
    },
    contact: {
      sectionNum: "06",
      sectionTitle: "Contact",
      headline: ["Let's build something", "", "remarkable", "together."],
      links: [
        { type: "email", label: "mario.rossi@email.com", href: "mailto:mario.rossi@email.com" },
        { type: "linkedin", label: "linkedin.com/in/mario-rossi", href: "https://linkedin.com/in/mario-rossi" },
        { type: "phone", label: "+39 333 123 4567", href: "tel:+393331234567" },
      ],
    },
    footer: {
      left: "© 2026 Mario Rossi",
      right: "Built with care · Milan, Italy",
    },
    backToProjects: "← Back to projects",
  },

  de: {
    nav: {
      about: "Über mich",
      experience: "Erfahrung",
      skills: "Skills",
      projects: "Projekte",
      education: "Ausbildung",
      contact: "Kontakt",
    },
    hero: {
      label: "Portfolio · Interaktiver Lebenslauf",
      name: "Mario",
      surname: "Rossi",
      role: "Finance & Strategy Analyst · Mailand",
      cta: "Kontakt aufnehmen",
      stats: {
        years: { num: "4+", label: "Jahre Erfahrung" },
        projects: { num: "12", label: "abgeschlossene Projekte" },
      },
      tags: ["Financial Modelling", "M&A", "Valuation", "Excel / VBA", "Python", "PowerBI"],
    },
    about: {
      sectionNum: "01",
      sectionTitle: "Über mich",
      paragraphs: [
        "Ich bin ein <strong>Finanzanalyst</strong> mit einer starken Leidenschaft für Daten und die Erstellung von Modellen, die komplexe Zahlen in klare Entscheidungen umwandeln. Ich habe Erfahrung in den Bereichen M&A, Unternehmensbewertung und strategische Planung gesammelt.",
        "In meiner Freizeit interessiere ich mich für <strong>Datenanalyse</strong> und entwickle kleine Tools zur Automatisierung repetitiver Aufgaben. Ich verbinde analytische Strenge mit Kreativität, um elegante Lösungen für konkrete Probleme zu finden.",
        "Ich suche nach neuen Herausforderungen in dynamischen Umfeldern, in denen ich wachsen, beitragen und jeden Tag dazulernen kann.",
      ],
      facts: [
        { label: "Verfügbarkeit", value: "Sofort · Vollzeit" },
        { label: "Standort", value: "Mailand · Umzugsbereit" },
        { label: "Sprachen", value: "Italienisch · Englisch (C1) · Französisch (B1)" },
        { label: "Interessen", value: "Finanzmärkte · Data Science · Laufen" },
      ],
    },
    experience: {
      sectionNum: "02",
      sectionTitle: "Erfahrung",
      items: [
        {
          period: "Jan 2023 — Heute",
          role: "Finance Analyst",
          company: "Società SpA · Mailand",
          desc: "Entwicklung von Finanzmodellen zur Bewertung potenzieller Akquisitionen. Unterstützung des Managements bei der Vorbereitung von Vorstandspräsentationen. Marktanalyse und Wettbewerbsvergleiche in 3+ Industriesektoren.",
        },
        {
          period: "Jul 2021 — Dez 2022",
          role: "Junior Analyst",
          company: "Consulting Firm Srl · Mailand",
          desc: "Mitarbeit an Financial Due Diligence Projekten und Unterstützung bei der Erstellung von Information Memoranda. Kundendatenbankpflege und periodisches Reporting.",
        },
        {
          period: "Mär 2021 — Jun 2021",
          role: "Praktikum — Finance Department",
          company: "Banca XYZ · Mailand",
          desc: "Curriculares Praktikum im Bereich Corporate Finance. Unterstützung bei der Erstellung von Pitch Books und Marktvergleichsanalysen.",
        },
      ],
    },
    skills: {
      sectionNum: "03",
      sectionTitle: "Skills",
      groups: [
        {
          title: "Finance & Analyse",
          items: [
            { name: "Financial Modelling", pct: 95 },
            { name: "Valuation (DCF, Comps)", pct: 90 },
            { name: "M&A / Due Diligence", pct: 80 },
            { name: "Corporate Finance", pct: 85 },
          ],
        },
        {
          title: "Tools & Software",
          items: [
            { name: "Excel / VBA", pct: 95 },
            { name: "PowerBI / Tableau", pct: 80 },
            { name: "Python (pandas, numpy)", pct: 70 },
            { name: "Bloomberg / Refinitiv", pct: 75 },
          ],
        },
        {
          title: "Soft Skills",
          items: [
            { name: "Problemlösung", pct: 95 },
            { name: "Kommunikation", pct: 85 },
            { name: "Teamarbeit", pct: 90 },
            { name: "Präsentationen", pct: 88 },
          ],
        },
      ],
    },
    projects: {
      sectionNum: "04",
      sectionTitle: "Projekte",
      cta: "Projekt erkunden",
      items: [
        {
          id: "portfolio-optimizer",
          symbol: "σ",
          tags: ["Python", "Finance"],
          title: "Portfolio Optimizer",
          desc: "Tool zur Optimierung von Aktienportfolios mit dem Markowitz-Modell.",
          fullDesc: "Dieses Projekt entstand aus dem Bedarf, die Modern Portfolio Theory praktisch und zugänglich anzuwenden. Das Tool berechnet die Markowitz-Effizienzgrenze aus historischen Daten, die automatisch über eine API heruntergeladen werden, und empfiehlt die optimale Allokation basierend auf dem Risikoprofil des Nutzers.",
          highlights: ["Berechnung der Effizienzgrenze", "Optimierte Sharpe Ratio", "Datenimport über Yahoo Finance API", "Interaktive Visualisierung mit Plotly"],
          tech: ["Python", "NumPy", "Pandas", "Plotly", "yfinance"],
          link: "https://github.com/mariorossi",
        },
        {
          id: "dcf-model",
          symbol: "Δ",
          tags: ["Excel", "VBA"],
          title: "Automatisiertes DCF-Modell",
          desc: "Erweitertes Excel-Template zur Unternehmensbewertung per DCF.",
          fullDesc: "Ein Excel-Template zur Vereinfachung und Beschleunigung der Unternehmensbewertung per Discounted Cash Flow. Das Modell importiert automatisch historische Finanzdaten und projiziert zukünftige Cashflows auf Basis anpassbarer Annahmen.",
          highlights: ["Automatischer Bilanzimport via API", "Szenarioanalyse (base/bull/bear)", "PDF-Bericht per Knopfdruck", "Übersichts-Dashboard mit Diagrammen"],
          tech: ["Excel", "VBA", "Power Query"],
          link: "https://github.com/mariorossi",
        },
        {
          id: "ma-monitor",
          symbol: "∑",
          tags: ["PowerBI", "Dashboard"],
          title: "M&A Market Monitor",
          desc: "Interaktives Dashboard zur Überwachung von M&A-Aktivitäten im italienischen Markt.",
          fullDesc: "Ein in PowerBI entwickeltes Dashboard zur Verfolgung und Analyse von M&A-Transaktionen auf dem italienischen Markt. Die Daten werden wöchentlich aktualisiert und können nach Sektor, Deal-Größe, Jahr und Region gefiltert werden.",
          highlights: ["Wöchentliche Datenaktualisierung", "Filter nach Sektor und Deal-Größe", "Historische Trends 2015–2024", "Automatisierter Berichtsexport"],
          tech: ["PowerBI", "Power Query", "DAX", "Excel"],
          link: "https://github.com/mariorossi",
        },
      ],
    },
    education: {
      sectionNum: "05",
      sectionTitle: "Ausbildung",
      items: [
        {
          year: "2019 — 2021",
          degree: "MSc Finance",
          school: "Università Bocconi · Mailand",
          note: "Abschlussarbeit über Corporate Valuation in M&A-Kontexten · 110/110",
        },
        {
          year: "2016 — 2019",
          degree: "BSc Wirtschaft & Management",
          school: "Università degli Studi di Milano",
          note: "Schwerpunkt Corporate Finance · 108/110",
        },
        {
          year: "2022",
          degree: "CFA Level I",
          school: "CFA Institute",
          note: "Bestanden im 90. Perzentil · Level II in Bearbeitung",
        },
        {
          year: "2020",
          degree: "Financial Modelling & Valuation",
          school: "FMVA® — Corporate Finance Institute",
          note: "Professionelle Online-Zertifizierung",
        },
      ],
    },
    contact: {
      sectionNum: "06",
      sectionTitle: "Kontakt",
      headline: ["Lassen Sie uns etwas", "", "Bedeutendes", "gemeinsam aufbauen."],
      links: [
        { type: "email", label: "mario.rossi@email.com", href: "mailto:mario.rossi@email.com" },
        { type: "linkedin", label: "linkedin.com/in/mario-rossi", href: "https://linkedin.com/in/mario-rossi" },
        { type: "phone", label: "+39 333 123 4567", href: "tel:+393331234567" },
      ],
    },
    footer: {
      left: "© 2026 Mario Rossi",
      right: "Mit Sorgfalt gebaut · Mailand, Italien",
    },
    backToProjects: "← Zurück zu den Projekten",
  },
};
