export const content = {
  it: {
    nav: {
      about: "Chi sono",
      experience: "Esperienza",
      skills: "Skills e Lingue",
      projects: "Progetti",
      sideprojects: "Progetti Personali",
      education: "Formazione",
      contact: "Contatti",
    },
    hero: {
      label: "Portfolio · CV Interattivo",
      name: "Andrea",
      surname: "Mili",
      role: "ESG & Sustainability Specialist · Monaco di Baviera, Germania",
      cta: "Contattami",
      downloadCv: "Scarica Curriculum Vitae",
      stats: {
        years: { num: "4+", label: "anni di esperienza" },
        projects: { num: "12", label: "progetti completati" },
      },
      tags: ["ESG", "Sostenibilità", "Valuation", "Excel / VBA", "Python", "PowerBI"],
    },
    about: {
      sectionNum: "01",
      sectionTitle: "Chi sono",
      paragraphs: [
        "Sono un <strong>esperto di sostenibilità e ESG</strong> con una forte passione per i dati e per la costruzione di modelli che trasformino numeri complessi in decisioni chiare. Ho maturato esperienza in ambito M&A, valutazione d'azienda e pianificazione strategica.",
        "Nel tempo libero mi interesso di <strong>data analysis</strong> e sviluppo piccoli strumenti per automatizzare attività ripetitive. Mi piace unire rigore analitico e creatività per trovare soluzioni eleganti a problemi concreti.",
        "Sono alla ricerca di nuove sfide in ambienti dinamici dove poter crescere, contribuire e continuare ad imparare ogni giorno.",
      ],
      facts: [],
    },
    experience: {
      sectionNum: "02",
      sectionTitle: "Esperienza",
      items: [
        {
          period: "Gen 2025 — Presente",
          role: "Senior Consultant Sustainable Finance & Public Sector",
          company: "Deloitte · Monaco di Baviera, Germania",
          desc: "Sviluppo di modelli finanziari per la valutazione di potenziali acquisizioni. Supporto al management nella preparazione di presentazioni per il CdA. Analisi di mercato e benchmarking competitivo per 3+ settori industriali.",
        },
        {
          period: "Nov 2022 — Dic 2024",
          role: "Senior Consultant ESG/Sustainability",
          company: "KPMG · Monaco di Baviera, Germania",
          desc: "Partecipazione a progetti di due diligence finanziaria e supporto nella redazione di information memorandum. Gestione database clienti e reportistica periodica.",
        },
        {
          period: "Mar 2021 — Giu 2021",
          role: "Environment, Health and Safety Specialist",
          company: "Tata Consultancy Services · Monaco di Baviera, Germania",
          desc: "Stage curriculare nell'area Corporate Finance. Supporto alla predisposizione di pitch book e analisi di comparabili di mercato.",
        },
      ],
    },
    skills: {
      sectionNum: "03",
      sectionTitle: "Skills e Lingue",
      groups: [
        {
          title: "Finance & Analisi",
          items: [
            { name: "Financial Modelling", pct: 95 },
            { name: "Valuation (DCF, Comps)", pct: 90 },
            { name: "M&A / Due Diligence", pct: 80 },
            { name: "Corporate Finance", pct: 85 },
          ],
        },
        {
          title: "Tool & Software",
          items: [
            { name: "Excel, PowerPoint", pct: 95 },
            { name: "Generative AI (Claude, Microsoft Copilot)", pct: 95 },
            { name: "PowerBI / Tableau", pct: 80 },
            { name: "Python (pandas, numpy)", pct: 70 },
            { name: "SQL", pct: 75 },
          ],
        },
        {
          title: "Soft Skills",
          items: [
            { name: "Problem Solving", pct: 95 },
            { name: "Comunicazione", pct: 85 },
            { name: "Teamwork", pct: 90 },
            { name: "Presentazioni", pct: 88 },
          ],
        },
        {
          title: "Lingue",
          items: [
            { name: "Italiano", pct: 100 },
            { name: "Inglese", pct: 90 },
            { name: "Tedesco", pct: 90 },
            { name: "Spagnolo", pct: 60 },
            { name: "Portoghese", pct: 20 },
            { name: "Gallese", pct: 20 },
          ],
        },
      ],
    },
    projects: {
      sectionNum: "04",
      sectionTitle: "Progetti",
      cta: "Scopri il progetto",
      items: [
        {
          id: "csrd-reporting",
          symbol: "σ",
          tags: ["Python", "Finance"],
          title: "CSRD Reporting",
          desc: "Tool per l'ottimizzazione di portafogli azionari tramite il modello di Markowitz.",
          fullDesc: "Questo progetto nasce dall'esigenza di applicare la Modern Portfolio Theory in modo pratico e accessibile. Il tool calcola la frontiera efficiente di Markowitz a partire da dati storici scaricati automaticamente via API, e suggerisce l'allocazione ottimale in base al profilo di rischio dell'utente.",
          highlights: ["Calcolo della frontiera efficiente", "Sharpe Ratio ottimizzato", "Importazione dati via Yahoo Finance API", "Visualizzazione interattiva con Plotly"],
          tech: ["Python", "NumPy", "Pandas", "Plotly", "yfinance"],
          link: "https://github.com/mariorossi",
          disclaimer: "Questo progetto è stato sviluppato a scopo personale e non rappresenta in alcun modo il lavoro svolto presso i miei datori di lavoro.",
        },
        {
          id: "lksg-compliance",
          symbol: "Δ",
          tags: ["Excel", "VBA"],
          title: "LkSG Compliance",
          desc: "Template Excel avanzato per la valutazione di società tramite DCF.",
          fullDesc: "Template Excel costruito per semplificare e velocizzare la valutazione di aziende tramite Discounted Cash Flow. Il modello importa automaticamente i dati finanziari storici e proietta i flussi di cassa futuri sulla base di assunzioni personalizzabili.",
          highlights: ["Import automatico bilanci via API", "Scenario analysis (base/bull/bear)", "Report PDF in un click", "Dashboard riassuntiva con grafici"],
          tech: ["Excel", "VBA", "Power Query"],
          link: "https://github.com/mariorossi",
          disclaimer: "Questo progetto è stato sviluppato a scopo personale e non rappresenta in alcun modo il lavoro svolto presso i miei datori di lavoro.",
        },
        {
          id: "ma-monitor",
          symbol: "∑",
          tags: ["PowerBI", "Dashboard"],
          title: "M&A Market Monitor",
          desc: "Dashboard interattiva per il monitoraggio delle operazioni M&A nel mercato italiano.",
          fullDesc: "Dashboard sviluppata in PowerBI per tracciare e analizzare le operazioni M&A sul mercato italiano. I dati vengono aggiornati settimanalmente e permettono di filtrare per settore, deal size, anno e area geografica.",
          highlights: ["Aggiornamento dati settimanale", "Filtri per settore e deal size", "Trend storici 2015–2024", "Export report automatizzato"],
          tech: ["PowerBI", "Power Query", "DAX", "Excel"],
          link: "https://github.com/mariorossi",
          disclaimer: "Questo progetto è stato sviluppato a scopo personale e non rappresenta in alcun modo il lavoro svolto presso i miei datori di lavoro.",
        },
      ],
    },
    sideProjects: {
      sectionNum: "05",
      sectionTitle: "Progetti Personali",
      cta: "Scopri il progetto",
      items: [
        {
          id: "side-project-1",
          symbol: "α",
          tags: ["ESG", "Excel"],
          title: "Progetto 1",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["Excel", "PowerBI"],
          link: "https://github.com/andreamili37",
          disclaimer: "Questo progetto è stato sviluppato a titolo personale.",
        },
        {
          id: "side-project-2",
          symbol: "β",
          tags: ["Python", "Data"],
          title: "Progetto 2",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["Python", "Pandas"],
          link: "https://github.com/andreamili37",
          disclaimer: "Questo progetto è stato sviluppato a titolo personale.",
        },
        {
          id: "side-project-3",
          symbol: "γ",
          tags: ["ESG", "Research"],
          title: "Progetto 3",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["PowerBI", "Excel"],
          link: "https://github.com/andreamili37",
          disclaimer: "Questo progetto è stato sviluppato a titolo personale.",
        },
      ],
    },
    education: {
      sectionNum: "06",
      sectionTitle: "Formazione",
      items: [
        {
          year: "2019 — 2022",
          degree: "MSc Politics and Technology",
          school: "Technical University of Munich · Monaco di Baviera, Germania",
          note: "Tesi su Corporate Valuation in contesti di M&A · Voto finale: 1.8 ",
        },
        {
          year: "2016 — 2019",
          degree: "BA Political and Administrative Sciences",
          school: "Università degli Studi di Trieste · Trieste, Italia",
          note: "Percorso in Finanza Aziendale · Voto finale: 107/110",
        },
        {
          year: "2023",
          degree: "ESG Expert (EBS)",
          school: "EBS University",
          note: "Certificazione professionale online",
        },
      ],
    },
    contact: {
      sectionNum: "07",
      sectionTitle: "Contatti",
      headline: ["Entriamo in contatto.", "", "", ""],
      links: [
        { type: "email", label: "andreamili@protonmail.com", href: "mailto:andreamili@protonmail.com" },
        { type: "linkedin", label: "linkedin.com/in/andrea-mili/", href: "https://www.linkedin.com/in/andrea-mili/" },
        { type: "phone", label: "+39 333 123 4567", href: "tel:+393331234567" },
      ],
    },
    footer: {
      left: "© 2026 Andrea Mili",
      right: "Costruito con cura · Monaco di Baviera, Germania",
    },
    backToProjects: "← Torna ai progetti",
  },

  en: {
    nav: {
      about: "About",
      experience: "Experience",
      skills: "Skills and Languages",
      projects: "Projects",
      sideprojects: "Side Projects",
      education: "Education",
      contact: "Contact",
    },
    hero: {
      label: "Portfolio · Interactive CV",
      name: "Andrea",
      surname: "Mili",
      role: "ESG & Sustainability Specialist · Munich, Germany",
      cta: "Get in touch",
      downloadCv: "Download CV",
      stats: {
        years: { num: "4+", label: "years of experience" },
        projects: { num: "12", label: "completed projects" },
      },
      tags: ["ESG", "Corporate Sustainability", "Compliance", "Strategy", "Python", "PowerBI"],
    },
    about: {
      sectionNum: "01",
      sectionTitle: "About me",
      paragraphs: [
        "I am an <strong>ESG and Sustainability Expert</strong> with a strong passion for data and building models that turn complex numbers into clear decisions. I have gained extensive experience in corporate sustainability projects ... .",
        "My strength lies in my adaptability (...)",
        "While I decided to dedicate my professional career to empowering the sustainable transition of organisations, I dedicate a great part of my free time to <strong>literature</strong>, both by reading fiction and non-fiction masterpieces, as well as producing my own pieces of creative writing. Examples of my productions can be read in my Substack pages.",
      ],
      facts: [],
    },
    experience: {
      sectionNum: "02",
      sectionTitle: "Professional Experience",
      items: [
        {
          period: "Jan 2025 — Present",
          role: "Senior Consultant Sustainable Finance & Public Sector",
          company: "Deloitte · Munich, Germany",
          desc: "Development of financial models for the evaluation of potential acquisitions. Support to management in preparing board presentations. Market analysis and competitive benchmarking across 3+ industrial sectors.",
        },
        {
          period: "Nov 2022 — Dec 2024",
          role: "Senior Associate ESG/Sustainability",
          company: "KPMG · Munich, Germany",
          desc: "Sustainability Reporting",
        },
        {
          period: "May 2021 — Jun 2022",
          role: "Environment, Health and Safety Officer",
          company: "Tata Consultancy Services · Munich, Germany",
          desc: "Curricular internship in the Corporate Finance division. Support in preparing pitch books and market comparables analysis.",
        },
      ],
    },
    skills: {
      sectionNum: "03",
      sectionTitle: "Skills and Languages",
      groups: [
        {
          title: "ESG and Sustainability",
          items: [
            { name: "ESG Regulations", pct: 95 },
            { name: "Valuation (DCF, Comps)", pct: 90 },
            { name: "M&A / Due Diligence", pct: 80 },
            { name: "Corporate Finance", pct: 85 },
          ],
        },
        {
          title: "Tools & Software",
          items: [
            { name: "Excel / VBA", pct: 95 },
            { name: "PowerBI", pct: 80 },
            { name: "Python (pandas, numpy)", pct: 70 },
            { name: "Generative AI tools (Claude, Microsoft Copilot)", pct: 75 },
          ],
        },
        {
          title: "Soft Skills",
          items: [
            { name: "Problem Solving", pct: 95 },
            { name: "Stakeholder Relationship Management", pct: 85 },
            { name: "Storytelling", pct: 90 },
            { name: "Presentations", pct: 88 },
          ],
        },
        {
          title: "Languages",
          items: [
            { name: "Italian", pct: 100 },
            { name: "English", pct: 90 },
            { name: "German", pct: 90 },
            { name: "Spanish", pct: 60 },
            { name: "Portuguese", pct: 20 },
            { name: "Welsh", pct: 20 },
          ],
        },
      ],
    },
    projects: {
      sectionNum: "04",
      sectionTitle: "Projects",
      cta: "Explore project",
      items: [
        {
          id: "csrd-reporting",
          symbol: "σ",
          tags: ["CSRD", "Compliance"],
          title: "CSRD Reporting",
          desc: "Supporting a large German company with all the necessary steps to produce a fully fledged CSRD report.",
          fullDesc: "Due to the Corporate Sustainability Directive (CSRD), ",
          highlights: ["Analysis of the company's structure", "Development of a concept for the production of a comprehensive Double Materiality Analysis", "Data import via Yahoo Finance API", "Interactive visualisation with Plotly"],
          tech: ["CSRD", "ESG", "Sustainability Reporting", "Sustainability Strategy", "Data Analysis"],
          link: "https://github.com/mariorossi",
          disclaimer: "The information in this section merely depicts my role within the project to showcase how I contributed to its successful realisation. It does not, in any way or form, indicate any client-sensitive information, nor any specific methodology developed within the company where I worked on this project.",
        },
        {
          id: "lksg-compliance",
          symbol: "Δ",
          tags: ["Excel", "VBA"],
          title: "Automated DCF Model",
          desc: "Advanced Excel template for company valuation via DCF.",
          fullDesc: "An Excel template built to simplify and speed up company valuation via Discounted Cash Flow. The model automatically imports historical financial data and projects future cash flows based on customisable assumptions.",
          highlights: ["Automatic financial statement import via API", "Scenario analysis (base/bull/bear)", "One-click PDF report", "Summary dashboard with charts"],
          tech: ["Excel", "VBA", "Power Query"],
          link: "https://github.com/mariorossi",
          disclaimer: "The information in this section merely depicts my role within the project to showcase how I contributed to its successful realisation. It does not, in any way or form, indicate any client-sensitive information, nor any specific methodology developed within the company where I worked on this project.",
        },
        {
          id: "ma-monitor",
          symbol: "∑",
          tags: ["PowerBI", "Dashboard"],
          title: "Non-financial reports audit",
          desc: "Interactive dashboard for monitoring M&A activity in the Italian market.",
          fullDesc: "A PowerBI dashboard developed to track and analyse M&A transactions in the Italian market. Data is updated weekly and can be filtered by sector, deal size, year and geography.",
          highlights: ["Weekly data updates", "Filters by sector and deal size", "Historical trends 2015–2024", "Automated report export"],
          tech: ["PowerBI", "Power Query", "DAX", "Excel"],
          link: "https://github.com/mariorossi",
          disclaimer: "The information in this section merely depicts my role within the project to showcase how I contributed to its successful realisation. It does not, in any way or form, indicate any client-sensitive information, nor any specific methodology developed within the company where I worked on this project.",
        },
      ],
    },
    sideProjects: {
      sectionNum: "05",
      sectionTitle: "Side Projects",
      cta: "Explore the project",
      items: [
        {
          id: "side-project-1",
          symbol: "α",
          tags: ["ESG", "Excel"],
          title: "Progetto 1",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["Excel", "PowerBI"],
          link: "https://github.com/andreamili37",
          disclaimer: "This project has been produced in my free time, using exclusively publicly available information (which are referenced), with my personal devices and intellectual knowledge. It does not, in any way or form, utilize client-specific information nor methodologies, knowledge or material produced by the companies I have been employed at. Moreover, this project does not represent any consultancy service I performed as freelancer: it is merely a way to showcase my skills and my interests.",
        },
        {
          id: "side-project-2",
          symbol: "β",
          tags: ["Python", "Data"],
          title: "Progetto 2",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["Python", "Pandas"],
          link: "https://github.com/andreamili37",
          disclaimer: "This project has been produced in my free time, using exclusively publicly available information (which are referenced), with my personal devices and intellectual knowledge. It does not, in any way or form, utilize client-specific information nor methodologies, knowledge or material produced by the companies I have been employed at. Moreover, this project does not represent any consultancy service I performed as freelancer: it is merely a way to showcase my skills and my interests.",
        },
        {
          id: "side-project-3",
          symbol: "γ",
          tags: ["ESG", "Research"],
          title: "Progetto 3",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["PowerBI", "Excel"],
          link: "https://github.com/andreamili37",
          disclaimer: "This project has been produced in my free time, using exclusively publicly available information (which are referenced), with my personal devices and intellectual knowledge. It does not, in any way or form, utilize client-specific information nor methodologies, knowledge or material produced by the companies I have been employed at. Moreover, this project does not represent any consultancy service I performed as freelancer: it is merely a way to showcase my skills and my interests.",
        },
      ],
    },
    education: {
      sectionNum: "06",
      sectionTitle: "Education",
      items: [
        {
          year: "2019 — 2022",
          degree: "MSc Politics and Technology",
          school: "Technical University of Munich· Germany",
          note: "Focus on Sustainability Transition and Corporate Sustainability · Final Grade: 1.8",
        },
        {
          year: "2015 — 2019",
          degree: "BA Political and Administrative Sciences",
          school: "Università degli Studi di Trieste",
          note: "Focus on EU Institutions and Policy Analysis · Final Grade: 107/110",
        },
        {
          year: "2023",
          degree: "ESG Expert (EBS)",
          school: "EBS University",
          note: "Professional ESG certification",
        },
      ],
    },
    contact: {
      sectionNum: "07",
      sectionTitle: "Contact",
      headline: ["Let's connect.", "", "", ""],
      links: [
        { type: "email", label: "andreamili@protonmail.com", href: "mailto:andreamili@protonmail.com" },
        { type: "linkedin", label: "linkedin.com/in/andrea-mili/", href: "https://www.linkedin.com/in/andrea-mili/" },
        { type: "phone", label: "+49 15141219336", href: "tel:+4915141219336" },
      ],
    },
    footer: {
      left: "© 2026 Andrea Mili",
      right: "Buten un Binnen, Wagen un Winnen · Munich, Germany",
    },
    backToProjects: "← Back to projects",
  },

  de: {
    nav: {
      about: "Über mich",
      experience: "Erfahrung",
      skills: "Skills und Sprachen",
      projects: "Projekte",
      sideprojects: "Eigenprojekte",
      education: "Ausbildung",
      contact: "Kontakt",
    },
    hero: {
      label: "Portfolio · Interaktiver Lebenslauf",
      name: "Andrea",
      surname: "Mili",
      role: "ESG- und Nachhaltigkeitsexperte · München, Deutschland",
      cta: "Kontakt aufnehmen",
      downloadCv: "Lebenslauf herunterladen",
      stats: {
        years: { num: "4+", label: "Jahre Erfahrung" },
        projects: { num: "20", label: "abgeschlossene Projekte" },
      },
      tags: ["ESG", "Nachhaltigkeit", "Compliance", "Excel / VBA", "Python", "PowerBI"],
    },
    about: {
      sectionNum: "01",
      sectionTitle: "Über mich",
      paragraphs: [
        "Ich bin ein <strong>Finanzanalyst</strong> mit einer starken Leidenschaft für Daten und die Erstellung von Modellen, die komplexe Zahlen in klare Entscheidungen umwandeln. Ich habe Erfahrung in den Bereichen M&A, Unternehmensbewertung und strategische Planung gesammelt.",
        "In meiner Freizeit interessiere ich mich für <strong>Datenanalyse</strong> und entwickle kleine Tools zur Automatisierung repetitiver Aufgaben. Ich verbinde analytische Strenge mit Kreativität, um elegante Lösungen für konkrete Probleme zu finden.",
        "Ich suche nach neuen Herausforderungen in dynamischen Umfeldern, in denen ich wachsen, beitragen und jeden Tag dazulernen kann.",
      ],
      facts: [],
    },
    experience: {
      sectionNum: "02",
      sectionTitle: "Erfahrung",
      items: [
        {
          period: "Jan 2025 — Heute",
          role: "Senior Consultant Sustainable Finance & Public Sector",
          company: "Deloitte · München, Deutschland",
          desc: "Entwicklung von Finanzmodellen zur Bewertung potenzieller Akquisitionen. Unterstützung des Managements bei der Vorbereitung von Vorstandspräsentationen. Marktanalyse und Wettbewerbsvergleiche in 3+ Industriesektoren.",
        },
        {
          period: "Jul 2021 — Dez 2022",
          role: "Senior Associate ESG/Sustainability",
          company: "KPMG · München, Deutschland",
          desc: "Mitarbeit an Financial Due Diligence Projekten und Unterstützung bei der Erstellung von Information Memoranda. Kundendatenbankpflege und periodisches Reporting.",
        },
        {
          period: "Mai 2021 — Jun 2022",
          role: "Praktikum — Finance Department",
          company: "Tata Consultancy Services · München, Deutschland",
          desc: "Curriculares Praktikum im Bereich Corporate Finance. Unterstützung bei der Erstellung von Pitch Books und Marktvergleichsanalysen.",
        },
      ],
    },
    skills: {
      sectionNum: "03",
      sectionTitle: "Skills und Sprachen",
      groups: [
        {
          title: "Finance & Analyse",
          items: [
            { name: "Financial Modelling", pct: 95 },
            { name: "Valuation (DCF, Comps)", pct: 90 },
            { name: "M&A / Due Diligence", pct: 80 },
            { name: "Corporate Finance", pct: 85 },
          ],
        },
        {
          title: "Tools & Software",
          items: [
            { name: "Excel / VBA", pct: 95 },
            { name: "PowerBI / Tableau", pct: 80 },
            { name: "Python (pandas, numpy)", pct: 70 },
            { name: "Bloomberg / Refinitiv", pct: 75 },
          ],
        },
        {
          title: "Soft Skills",
          items: [
            { name: "Problemlösung", pct: 95 },
            { name: "Kommunikation", pct: 85 },
            { name: "Teamarbeit", pct: 90 },
            { name: "Präsentationen", pct: 88 },
          ],
        },
        {
          title: "Sprachen",
          items: [
            { name: "Italienisch", pct: 100 },
            { name: "Englisch", pct: 90 },
            { name: "Deutsch", pct: 90 },
            { name: "Spanisch", pct: 60 },
            { name: "Portugiesisch", pct: 20 },
            { name: "Walisisch", pct: 20 },
          ],
        },
      ],
    },
    projects: {
      sectionNum: "04",
      sectionTitle: "Projekte",
      cta: "Projekt erkunden",
      items: [
        {
          id: "csrd-reporting",
          symbol: "σ",
          tags: ["Python", "Finance"],
          title: "ESG-Ratings Vergleich",
          desc: "Tool zur Optimierung von Aktienportfolios mit dem Markowitz-Modell.",
          fullDesc: "Dieses Projekt entstand aus dem Bedarf, die Modern Portfolio Theory praktisch und zugänglich anzuwenden. Das Tool berechnet die Markowitz-Effizienzgrenze aus historischen Daten, die automatisch über eine API heruntergeladen werden, und empfiehlt die optimale Allokation basierend auf dem Risikoprofil des Nutzers.",
          highlights: ["Berechnung der Effizienzgrenze", "Optimierte Sharpe Ratio", "Datenimport über Yahoo Finance API", "Interaktive Visualisierung mit Plotly"],
          tech: ["Python", "NumPy", "Pandas", "Plotly", "yfinance"],
          link: "https://github.com/mariorossi",
          disclaimer: "Questo progetto è stato sviluppato a scopo personale e non rappresenta in alcun modo il lavoro svolto presso i miei datori di lavoro.",
        },
        {
          id: "lksg-compliance",
          symbol: "Δ",
          tags: ["Excel", "VBA"],
          title: "Automatisiertes DCF-Modell",
          desc: "Erweitertes Excel-Template zur Unternehmensbewertung per DCF.",
          fullDesc: "Ein Excel-Template zur Vereinfachung und Beschleunigung der Unternehmensbewertung per Discounted Cash Flow. Das Modell importiert automatisch historische Finanzdaten und projiziert zukünftige Cashflows auf Basis anpassbarer Annahmen.",
          highlights: ["Automatischer Bilanzimport via API", "Szenarioanalyse (base/bull/bear)", "PDF-Bericht per Knopfdruck", "Übersichts-Dashboard mit Diagrammen"],
          tech: ["Excel", "VBA", "Power Query"],
          link: "https://github.com/mariorossi",
          disclaimer: "Questo progetto è stato sviluppato a scopo personale e non rappresenta in alcun modo il lavoro svolto presso i miei datori di lavoro.",
        },
        {
          id: "ma-monitor",
          symbol: "∑",
          tags: ["PowerBI", "Dashboard"],
          title: "M&A Market Monitor",
          desc: "Interaktives Dashboard zur Überwachung von M&A-Aktivitäten im italienischen Markt.",
          fullDesc: "Ein in PowerBI entwickeltes Dashboard zur Verfolgung und Analyse von M&A-Transaktionen auf dem italienischen Markt. Die Daten werden wöchentlich aktualisiert und können nach Sektor, Deal-Größe, Jahr und Region gefiltert werden.",
          highlights: ["Wöchentliche Datenaktualisierung", "Filter nach Sektor und Deal-Größe", "Historische Trends 2015–2024", "Automatisierter Berichtsexport"],
          tech: ["PowerBI", "Power Query", "DAX", "Excel"],
          link: "https://github.com/mariorossi",
          disclaimer: "Questo progetto è stato sviluppato a scopo personale e non rappresenta in alcun modo il lavoro svolto presso i miei datori di lavoro.",
        },
      ],
    },
    sideProjects: {
      sectionNum: "05",
      sectionTitle: "Eigenprojekte",
      cta: "Projekt erkunden",
      items: [
        {
          id: "side-project-1",
          symbol: "α",
          tags: ["ESG", "Excel"],
          title: "Progetto 1",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["Excel", "PowerBI"],
          link: "https://github.com/andreamili37",
          disclaimer: "Questo progetto è stato sviluppato a titolo personale.",
        },
        {
          id: "side-project-2",
          symbol: "β",
          tags: ["Python", "Data"],
          title: "Progetto 2",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["Python", "Pandas"],
          link: "https://github.com/andreamili37",
          disclaimer: "Questo progetto è stato sviluppato a titolo personale.",
        },
        {
          id: "side-project-3",
          symbol: "γ",
          tags: ["ESG", "Research"],
          title: "Progetto 3",
          desc: "Breve descrizione del progetto personale.",
          fullDesc: "Descrizione estesa del progetto.",
          highlights: ["Highlight 1", "Highlight 2", "Highlight 3"],
          tech: ["PowerBI", "Excel"],
          link: "https://github.com/andreamili37",
          disclaimer: "Questo progetto è stato sviluppato a titolo personale.",
        },
      ],
    },
    education: {
      sectionNum: "06",
      sectionTitle: "Ausbildung",
      items: [
        {
          year: "2019 — 2021",
          degree: "MSc Politics and Technology",
          school: "Technische Universität München · München, Deutschland",
          note: "Abschlussarbeit über Corporate Valuation in M&A-Kontexten · 110/110",
        },
        {
          year: "2016 — 2019",
          degree: "BA Politikwissenschaft",
          school: "Universität Triest · Triest, Italien ",
          note: "Schwerpunkt Corporate Finance · 108/110",
        },
        {
          year: "2020",
          degree: "Financial Modelling & Valuation",
          school: "FMVA® — Corporate Finance Institute",
          note: "Professionelle Online-Zertifizierung",
        },
      ],
    },
    contact: {
      sectionNum: "07",
      sectionTitle: "Kontakt",
      headline: ["Lassen Sie uns etwas", "", "Bedeutendes", "gemeinsam aufbauen."],
      links: [
        { type: "email", label: "andreamili@protonmail.com", href: "mailto:andreamili@protonmail.com" },
        { type: "linkedin", label: "linkedin.com/in/andrea-mili/", href: "https://www.linkedin.com/in/andrea-mili/" },
        { type: "phone", label: "+39 333 123 4567", href: "tel:+393331234567" },
      ],
    },
    footer: {
      left: "© 2026 Andrea Mili",
      right: "Mit Sorgfalt gebaut · München, Deutschland",
    },
    backToProjects: "← Zurück zu den Projekten",
  },
};
